//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_linh_kiện_máy_tính
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSp { get; set; }
        public string MaLoai { get; set; }
        public string TenSp { get; set; }
        public byte[] Hinh { get; set; }
        public int Gia { get; set; }
        public int SoLuong { get; set; }
    
        public virtual PhanLoai PhanLoai { get; set; }
    }
}
